$axure.loadCurrentPage({
  "url":"选择参考书籍.html",
  "generationDate":new Date(1527954929000.17),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"60a37fb088a2425abef85cd0c45eb094",
    "type":"Axure:Page",
    "name":"选择参考书籍",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"69e1141a63454813b5084e7dcb10b5ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF99CCCC},
            "location":{
              "x":40,
              "y":30},
            "size":{
              "width":720,
              "height":310}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaa1b25abd5e4ae3926778b838a33c26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99CCCC},
                "location":{
                  "x":40,
                  "y":30},
                "size":{
                  "width":720,
                  "height":310}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择参考书籍/u0.png"}},
{
          "id":"d995b83910d7481aa046589f621d4ebc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":314,
              "y":43},
            "size":{
              "width":193,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62f50c5397d8457a871c51265fd54ebc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":314,
                  "y":43},
                "size":{
                  "width":193,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"522794d6f5ba475799a54e05b687ae53",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":551,
              "y":50},
            "size":{
              "width":149,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99fcb896d555440d8fbe8cceab6ce6c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":551,
                  "y":50},
                "size":{
                  "width":149,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee2f6474cf60433d9c58936319a1f522",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":710,
              "y":50},
            "size":{
              "width":30,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fb121f707b74c1b9ecbf3b492388114",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":710,
                  "y":50},
                "size":{
                  "width":30,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94ad8e4cfd7d417797c9db0550de9a5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":250,
              "y":130},
            "size":{
              "width":80,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e511f45892f54555a9422fa7f8877e8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":250,
                  "y":130},
                "size":{
                  "width":80,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc0f959787c34cb789e7c1aeb28cf934",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":250,
              "y":191},
            "size":{
              "width":80,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6340d78d442e432bb78217e28e60c798",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":250,
                  "y":191},
                "size":{
                  "width":80,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79b1489916e9499ab421f98d92920968",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":250,
              "y":241},
            "size":{
              "width":80,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2359638f9c094e6aad5b050f4effe974",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":250,
                  "y":241},
                "size":{
                  "width":80,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7dcec77bafa148e8acab168a2502ec9d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":128.5},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"f431ed617bf04235a19076acce3f1550",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":189.5},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"23f39c27e54348b397acd05c7da17a91",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":239.5},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"d8a908af65494d05b16e83b55ea53a31",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":290,
              "y":290},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"34954a157c5848c293150adb819d4c46",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":440,
              "y":290},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 老师",
                      "target":{
                        "targetType":"page",
                        "url":"老师.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "69e1141a63454813b5084e7dcb10b5ca":{
      "scriptId":"u0"},
    "aaa1b25abd5e4ae3926778b838a33c26":{
      "scriptId":"u1"},
    "d995b83910d7481aa046589f621d4ebc":{
      "scriptId":"u2"},
    "62f50c5397d8457a871c51265fd54ebc":{
      "scriptId":"u3"},
    "522794d6f5ba475799a54e05b687ae53":{
      "scriptId":"u4"},
    "99fcb896d555440d8fbe8cceab6ce6c9":{
      "scriptId":"u5"},
    "ee2f6474cf60433d9c58936319a1f522":{
      "scriptId":"u6"},
    "1fb121f707b74c1b9ecbf3b492388114":{
      "scriptId":"u7"},
    "94ad8e4cfd7d417797c9db0550de9a5c":{
      "scriptId":"u8"},
    "e511f45892f54555a9422fa7f8877e8b":{
      "scriptId":"u9"},
    "cc0f959787c34cb789e7c1aeb28cf934":{
      "scriptId":"u10"},
    "6340d78d442e432bb78217e28e60c798":{
      "scriptId":"u11"},
    "79b1489916e9499ab421f98d92920968":{
      "scriptId":"u12"},
    "2359638f9c094e6aad5b050f4effe974":{
      "scriptId":"u13"},
    "7dcec77bafa148e8acab168a2502ec9d":{
      "scriptId":"u14"},
    "f431ed617bf04235a19076acce3f1550":{
      "scriptId":"u15"},
    "23f39c27e54348b397acd05c7da17a91":{
      "scriptId":"u16"},
    "d8a908af65494d05b16e83b55ea53a31":{
      "scriptId":"u17"},
    "34954a157c5848c293150adb819d4c46":{
      "scriptId":"u18"}}});