$axure.loadCurrentPage({
  "url":"学生.html",
  "generationDate":new Date(1527954929782.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"39ba301659d242ac9c7be85b65336574",
    "type":"Axure:Page",
    "name":"学生",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"38ca0731d6f148d4b77baf50dde36d4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF99CCCC},
            "location":{
              "x":80,
              "y":40},
            "size":{
              "width":630,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c737cf4b23b74bdc8468bce3d99fa1aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99CCCC},
                "location":{
                  "x":80,
                  "y":40},
                "size":{
                  "width":630,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/老师/u0.png"}},
{
          "id":"8fccd6d5e4db4844baafeb8a49758ba4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":310,
              "y":80},
            "size":{
              "width":169,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6aca1d0d6754f37928f42667cd20048",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":310,
                  "y":80},
                "size":{
                  "width":169,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a5c5d138a434533a91cf453f9efe4bf",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":167},
            "size":{
              "width":300,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0713ae753904d898108676a2e8d3226",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":300,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a92575b5ed09472dba84faaa715b70cd",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF9999FF},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5b683ea3f6b14c06b2ada969178cda6d",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF9999FF},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 查看所选课程",
                              "target":{
                                "targetType":"page",
                                "url":"查看所选课程.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/老师/u4.png"}},
{
                  "id":"f116a4b0a00241af894e2712c22fd683",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF9999FF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7312faf08d9340948ca2292e85e3cbef",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF9999FF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 查看成绩",
                              "target":{
                                "targetType":"page",
                                "url":"查看成绩.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/老师/u4.png"}},
{
                  "id":"a65889a0ed9c4de4a65d01e2c32eb36f",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF9999FF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"449d3fa948ac4bb5908881b95dee11ae",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF9999FF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 选择课程",
                              "target":{
                                "targetType":"page",
                                "url":"选择课程.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/老师/u10.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "38ca0731d6f148d4b77baf50dde36d4b":{
      "scriptId":"u0"},
    "c737cf4b23b74bdc8468bce3d99fa1aa":{
      "scriptId":"u1"},
    "8fccd6d5e4db4844baafeb8a49758ba4":{
      "scriptId":"u2"},
    "f6aca1d0d6754f37928f42667cd20048":{
      "scriptId":"u3"},
    "3a5c5d138a434533a91cf453f9efe4bf":{
      "scriptId":"u4"},
    "d0713ae753904d898108676a2e8d3226":{
      "scriptId":"u5"},
    "a92575b5ed09472dba84faaa715b70cd":{
      "scriptId":"u6"},
    "5b683ea3f6b14c06b2ada969178cda6d":{
      "scriptId":"u7"},
    "f116a4b0a00241af894e2712c22fd683":{
      "scriptId":"u8"},
    "7312faf08d9340948ca2292e85e3cbef":{
      "scriptId":"u9"},
    "a65889a0ed9c4de4a65d01e2c32eb36f":{
      "scriptId":"u10"},
    "449d3fa948ac4bb5908881b95dee11ae":{
      "scriptId":"u11"}}});