$axure.loadCurrentPage({
  "url":"评定成绩.html",
  "generationDate":new Date(1527954928785.35),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d703f2dd8848472fa3d1ab8a6fd4ca9d",
    "type":"Axure:Page",
    "name":"评定成绩",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"40fe72f72ea54562bfe7bbf8e7ef32af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF99CCCC},
            "location":{
              "x":70.5,
              "y":20},
            "size":{
              "width":680,
              "height":310}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91cbdf9005644100be297b317fe4523c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99CCCC},
                "location":{
                  "x":70.5,
                  "y":20},
                "size":{
                  "width":680,
                  "height":310}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评定成绩/u0.png"}},
{
          "id":"e60f159e260f437f88540eae5dac47e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":346,
              "y":50},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66a669acb53744b390b7295c9425b666",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":346,
                  "y":50},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ad38de4ad2f4ea5b5c62c54d2a6c25e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":690,
              "y":50},
            "size":{
              "width":30,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e6161cde466421ab3105ad411fc6dcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":690,
                  "y":50},
                "size":{
                  "width":30,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"895c3b6bc345470c98339537a64e937a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":520,
              "y":50},
            "size":{
              "width":149,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d933616afc014b1eb19b901b0e74400e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":520,
                  "y":50},
                "size":{
                  "width":149,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cfb88daf5ff8478a972c33c1967de249",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":70,
              "y":82},
            "size":{
              "width":143,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2248a05abb1449b900e97981f7b02de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":70,
                  "y":82},
                "size":{
                  "width":143,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ef55ecbb9bf46fdaafc77c4f37af06a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":240,
              "y":137},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09da3f40e6b44a8bb2c950c52d47b5c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":240,
                  "y":137},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31b7eb4ae5d641e7be2b7790db55aed7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":240,
              "y":182},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de7973c0531444d398f9e4a544714c8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":240,
                  "y":182},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3d08afb2ca34e409410de23672cc17a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":240,
              "y":231},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9240261366aa41dba86794e3fc41e107",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":240,
                  "y":231},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ae58fd5121540c6a8e0c33fa0e7585a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":134},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f12ceca6098546f8a9f2ae6106a36861",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":185},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2c081aa759f44f1e903343901026b808",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":228},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8c1edf93cecf4d7481171204eed1ab8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":240,
              "y":263},
            "size":{
              "width":420,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97ce7cd143044fdf985ba85fcbc0b891",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":240,
                  "y":263},
                "size":{
                  "width":420,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd40be2c9b0c4f79ba2c90c6df348a28",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":520,
              "y":295},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"01d8f0547b0740229ef6d9f7ef999032",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":630,
              "y":295},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 老师",
                      "target":{
                        "targetType":"page",
                        "url":"老师.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "40fe72f72ea54562bfe7bbf8e7ef32af":{
      "scriptId":"u0"},
    "91cbdf9005644100be297b317fe4523c":{
      "scriptId":"u1"},
    "e60f159e260f437f88540eae5dac47e2":{
      "scriptId":"u2"},
    "66a669acb53744b390b7295c9425b666":{
      "scriptId":"u3"},
    "4ad38de4ad2f4ea5b5c62c54d2a6c25e":{
      "scriptId":"u4"},
    "4e6161cde466421ab3105ad411fc6dcc":{
      "scriptId":"u5"},
    "895c3b6bc345470c98339537a64e937a":{
      "scriptId":"u6"},
    "d933616afc014b1eb19b901b0e74400e":{
      "scriptId":"u7"},
    "cfb88daf5ff8478a972c33c1967de249":{
      "scriptId":"u8"},
    "f2248a05abb1449b900e97981f7b02de":{
      "scriptId":"u9"},
    "5ef55ecbb9bf46fdaafc77c4f37af06a":{
      "scriptId":"u10"},
    "09da3f40e6b44a8bb2c950c52d47b5c0":{
      "scriptId":"u11"},
    "31b7eb4ae5d641e7be2b7790db55aed7":{
      "scriptId":"u12"},
    "de7973c0531444d398f9e4a544714c8b":{
      "scriptId":"u13"},
    "d3d08afb2ca34e409410de23672cc17a":{
      "scriptId":"u14"},
    "9240261366aa41dba86794e3fc41e107":{
      "scriptId":"u15"},
    "7ae58fd5121540c6a8e0c33fa0e7585a":{
      "scriptId":"u16"},
    "f12ceca6098546f8a9f2ae6106a36861":{
      "scriptId":"u17"},
    "2c081aa759f44f1e903343901026b808":{
      "scriptId":"u18"},
    "8c1edf93cecf4d7481171204eed1ab8a":{
      "scriptId":"u19"},
    "97ce7cd143044fdf985ba85fcbc0b891":{
      "scriptId":"u20"},
    "cd40be2c9b0c4f79ba2c90c6df348a28":{
      "scriptId":"u21"},
    "01d8f0547b0740229ef6d9f7ef999032":{
      "scriptId":"u22"}}});