@startuml
title 基于GitHub的实验管理平台--老师实验评分用例的顺序图
actor users
users-->Subject:选择课程
Subject -> Teacher:该课程对应的老师

Teacher-->student
student-->Teacher:返回所有的学生
student-->test
test-->student:返回每个学生的成绩
@enduml
