$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1527954926881),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7d5c01c7ab334d52812fbeb8dbbc0014",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7595521d2d9749268815ef3f5a983134",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF99CCCC},
            "location":{
              "x":70,
              "y":10},
            "size":{
              "width":680,
              "height":340},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afbdb920181a4bf1b12f343a45d39104",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99CCCC},
                "location":{
                  "x":70,
                  "y":10},
                "size":{
                  "width":680,
                  "height":340},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "linePattern":"dotted"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"fe57eae5877943a9bf8f3b9a1d50e3f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":214,
              "y":23},
            "size":{
              "width":392,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32890e7037ab4ee6a629ea3a86dc2fc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":214,
                  "y":23},
                "size":{
                  "width":392,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8981a691938a4c0eb0d9edfd702d9f81",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Adobe 黑体 Std R', 'Adobe 黑体 Std'",
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF9999FF},
            "location":{
              "x":350,
              "y":108},
            "size":{
              "width":120,
              "height":41},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"654d3937bfa5472b9618ea45534ccf64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Adobe 黑体 Std R', 'Adobe 黑体 Std'",
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF9999FF},
                "location":{
                  "x":350,
                  "y":108},
                "size":{
                  "width":120,
                  "height":41},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 老师",
                      "target":{
                        "targetType":"page",
                        "url":"老师.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"4fd0559b44d14779995480c9a8358004",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Adobe 黑体 Std R', 'Adobe 黑体 Std'",
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF9999FF},
            "location":{
              "x":350,
              "y":164},
            "size":{
              "width":120,
              "height":41},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f20ba2ad53534f6da24ebc29c5aaf43a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Adobe 黑体 Std R', 'Adobe 黑体 Std'",
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF9999FF},
                "location":{
                  "x":350,
                  "y":164},
                "size":{
                  "width":120,
                  "height":41},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 学生",
                      "target":{
                        "targetType":"page",
                        "url":"学生.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"1af3cc93c92b40c2866a5955fa837867",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Adobe 黑体 Std R', 'Adobe 黑体 Std'",
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF9999FF},
            "location":{
              "x":320,
              "y":230},
            "size":{
              "width":180,
              "height":41},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e867b918b1b846bf94a4ab0c863c7171",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Adobe 黑体 Std R', 'Adobe 黑体 Std'",
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF9999FF},
                "location":{
                  "x":320,
                  "y":230},
                "size":{
                  "width":180,
                  "height":41},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改用户信息",
                      "target":{
                        "targetType":"page",
                        "url":"修改用户信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u8.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "7595521d2d9749268815ef3f5a983134":{
      "scriptId":"u0"},
    "afbdb920181a4bf1b12f343a45d39104":{
      "scriptId":"u1"},
    "fe57eae5877943a9bf8f3b9a1d50e3f2":{
      "scriptId":"u2"},
    "32890e7037ab4ee6a629ea3a86dc2fc8":{
      "scriptId":"u3"},
    "8981a691938a4c0eb0d9edfd702d9f81":{
      "scriptId":"u4"},
    "654d3937bfa5472b9618ea45534ccf64":{
      "scriptId":"u5"},
    "4fd0559b44d14779995480c9a8358004":{
      "scriptId":"u6"},
    "f20ba2ad53534f6da24ebc29c5aaf43a":{
      "scriptId":"u7"},
    "1af3cc93c92b40c2866a5955fa837867":{
      "scriptId":"u8"},
    "e867b918b1b846bf94a4ab0c863c7171":{
      "scriptId":"u9"}}});