$axure.loadCurrentPage({
  "url":"选择课程.html",
  "generationDate":new Date(1527954928118.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"dc3c02e0c2da4271a7e3acf5a61e214f",
    "type":"Axure:Page",
    "name":"选择课程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1ce18c8389d94f9c8e9a1a0062d0b91b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF99CCCC},
            "location":{
              "x":90,
              "y":30},
            "size":{
              "width":670,
              "height":310}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5d7541029a849feae7116b7af228eeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99CCCC},
                "location":{
                  "x":90,
                  "y":30},
                "size":{
                  "width":670,
                  "height":310}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看成绩/u0.png"}},
{
          "id":"21913a09115341c69aacdae8e9a7a68e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":350.5,
              "y":43},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f2df740394d4229991169f692f2e30a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":350.5,
                  "y":43},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7eabbed73e8a4c1fbf765318de7bb1e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":270,
              "y":134},
            "size":{
              "width":70,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ee55f1d20e94a95b6285bc2cf890b0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":270,
                  "y":134},
                "size":{
                  "width":70,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f41cdd456ba4c909fe03828585e9b37",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":270,
              "y":201},
            "size":{
              "width":80,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9630d175d2a64ebeb62335de54278cf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":270,
                  "y":201},
                "size":{
                  "width":80,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b17a1774696d4396b9c0452f314d13b0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":131},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4aec6f0ee02241d58a33986996eeaf66",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":201},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"4d8842cde33446fc929a5013a2cec6c2",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":280,
              "y":260},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bfcf6cee56324d9f8328a3e78fc2df5d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":450,
              "y":260},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "1ce18c8389d94f9c8e9a1a0062d0b91b":{
      "scriptId":"u0"},
    "f5d7541029a849feae7116b7af228eeb":{
      "scriptId":"u1"},
    "21913a09115341c69aacdae8e9a7a68e":{
      "scriptId":"u2"},
    "5f2df740394d4229991169f692f2e30a":{
      "scriptId":"u3"},
    "7eabbed73e8a4c1fbf765318de7bb1e3":{
      "scriptId":"u4"},
    "7ee55f1d20e94a95b6285bc2cf890b0b":{
      "scriptId":"u5"},
    "6f41cdd456ba4c909fe03828585e9b37":{
      "scriptId":"u6"},
    "9630d175d2a64ebeb62335de54278cf2":{
      "scriptId":"u7"},
    "b17a1774696d4396b9c0452f314d13b0":{
      "scriptId":"u8"},
    "4aec6f0ee02241d58a33986996eeaf66":{
      "scriptId":"u9"},
    "4d8842cde33446fc929a5013a2cec6c2":{
      "scriptId":"u10"},
    "bfcf6cee56324d9f8328a3e78fc2df5d":{
      "scriptId":"u11"}}});