$axure.loadCurrentPage({
  "url":"查看成绩.html",
  "generationDate":new Date(1527954927903.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6a16b7664a484bfbb28a22ca5f0f8285",
    "type":"Axure:Page",
    "name":"查看成绩",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4e9f12686dbe4fb4bdf0f90cb4a43487",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF99CCCC},
            "location":{
              "x":69.5,
              "y":30},
            "size":{
              "width":670,
              "height":310}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91c9a537a12a46ce81721c21f8f14480",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99CCCC},
                "location":{
                  "x":69.5,
                  "y":30},
                "size":{
                  "width":670,
                  "height":310}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看成绩/u0.png"}},
{
          "id":"ab39dddc5f5644e49f8fc0276faaf132",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":340.5,
              "y":40},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec1df21a4cee441cbf5f089e713feb60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":340.5,
                  "y":40},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6c2061b803546b99284b8d7873fc91e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":135},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4c739dad759f47cba039614754b96b40",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":250,
              "y":140},
            "size":{
              "width":60,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35d1f36b2caa4a1e828f295ebdc6d771",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":250,
                  "y":140},
                "size":{
                  "width":60,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d193babcec84500b296c12433833195",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":250,
              "y":230},
            "size":{
              "width":80,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"033beeb8978f4cfbb123548fd0007c28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":250,
                  "y":230},
                "size":{
                  "width":80,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8d3e92181b6422b8ddf020d13c51b26",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":250,
              "y":190},
            "size":{
              "width":70,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66ff68881d5746f98ef0f1484ac68c38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":250,
                  "y":190},
                "size":{
                  "width":70,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"648f252c53724337a7b614d8721a9ea4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":185.5},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8150cbf8bb89449aa5bf34591259151d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":225.5},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"64ce1f3ab4b1493c8a72fcaff3f22121",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":280,
              "y":280},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7a5f6779e6de48f3bc35df2a50ccb3eb",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":440,
              "y":280},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 老师",
                      "target":{
                        "targetType":"page",
                        "url":"老师.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "4e9f12686dbe4fb4bdf0f90cb4a43487":{
      "scriptId":"u0"},
    "91c9a537a12a46ce81721c21f8f14480":{
      "scriptId":"u1"},
    "ab39dddc5f5644e49f8fc0276faaf132":{
      "scriptId":"u2"},
    "ec1df21a4cee441cbf5f089e713feb60":{
      "scriptId":"u3"},
    "c6c2061b803546b99284b8d7873fc91e":{
      "scriptId":"u4"},
    "4c739dad759f47cba039614754b96b40":{
      "scriptId":"u5"},
    "35d1f36b2caa4a1e828f295ebdc6d771":{
      "scriptId":"u6"},
    "8d193babcec84500b296c12433833195":{
      "scriptId":"u7"},
    "033beeb8978f4cfbb123548fd0007c28":{
      "scriptId":"u8"},
    "e8d3e92181b6422b8ddf020d13c51b26":{
      "scriptId":"u9"},
    "66ff68881d5746f98ef0f1484ac68c38":{
      "scriptId":"u10"},
    "648f252c53724337a7b614d8721a9ea4":{
      "scriptId":"u11"},
    "8150cbf8bb89449aa5bf34591259151d":{
      "scriptId":"u12"},
    "64ce1f3ab4b1493c8a72fcaff3f22121":{
      "scriptId":"u13"},
    "7a5f6779e6de48f3bc35df2a50ccb3eb":{
      "scriptId":"u14"}}});